import { Ride, Transaction, ChatMessage, UserProfile, AppNotification, Review } from './types';

export const mockUser: UserProfile = {
  name: 'Julien Lefebvre',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAby0Rn8erk2YZBcKxcCOedz-o-J6LkLv9pNJHNr8WTixy0vSQWlI9q17tx8gNlqjP8gB7upxPYu-lZl0AxubQNlOu4QZvsdqTlKqg90BGRf34GdzTfOQviurxW9xI2HsUWvSidmM5RMm3ASp0B21R39psB88FP_b1GqjCO40iLnPGVLSKy0L0aQI89xzTyRsbeJ9VOflAxlcZlpaIRHdf85MFqjf2NiteauDeEW1pD_glxEb3cQFqFblM0nh8obJ0U3rq_7YkC8CI',
  memberSince: 'Mars 2023',
  reliabilityScore: 98,
  totalTrips: 142,
  cancellationRate: 1.2,
  badge: 'Conducteur fiable',
};

const now = Date.now();

export const mockRides: Ride[] = [
  {
    id: '1',
    departure: 'Gare du Nord',
    destination: 'Aéroport Charles de Gaulle',
    departureCoords: { lat: 48.8809, lng: 2.3553 },
    destinationCoords: { lat: 49.0097, lng: 2.5479 },
    date: 'Demain',
    time: '08:30',
    price: 24.50,
    seats: 3,
    status: 'confirmed',
    driver: {
      name: 'Marc-Antoine P.',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2tjEgAiOsrODrGShPZTq1Q7IcxFptJw_NPM-ma_jZK-0tLYDdfWB0dgqI4nhCEiR2HPf-LdBUjpNE6G4HaqOVl4Z5pSPSDW1LJ-l3nHggr24JXJO61tEq_t6w9JG_krZLPyewj0a_iJiYF9Mv48bbBKT7XeiJ7mqKCWQ1Ic_CEuQKe1l5-ld6YozRjfNT1sH07lKlVIZVUFmWMOZwaLcEdSpIwGdjhtdFawKjTftFjpX4EaUertKCBFlKBR0-gs9xMfqw80rtBho',
      rating: 4.9,
      trips: 1240,
      reliabilityScore: 98,
      vehicle: {
        model: 'Tesla Model 3',
        color: 'Blanc Nacré',
        type: 'Électrique',
        plate: 'AA-123-RR',
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDCDalVf-vU-oSYArNn6-MGd1Rzp7mf2dFAvAVV3HMawhO8BHumuj1hvkxIO3d-FE67q7rJHXPmDb4FXMvQFADcbL0kp_sc5nUU7sPBLdzayE45If_REYZMEiSgQIdEEE7U5LRGf6QooM5c9kUHzycPMP9_rXI6UmdFr3djSpx69Z0tA4rIIVkr6cLuo1G5pyh45C4WQGwD-K4EOQ2JHGQZ01aRybw3WJsd5TfKwiu75aCk3Ekvao1243Rn8QT37PJjXsoIbOSwNmo',
      },
    },
    createdAt: now - 5 * 60 * 1000,
    mapImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDwD4YBoKsUmHAeDZ3-VygZNbCjvQrlIHcE-2OcQQ6usgFdPslRKYlDuzA35tr_Xn5nMZWIH1jt1w4YZYTOKXYOTz_E_xHtygDcoNhDeZ5HMHCMYvpHwQhzEEESLUHKuh_7NqDXW7jgxZbebaowH6Emu9wexRj7u-Gs5LVex_E7jy_UKhiy7YU3SBRn27y6CEyBOgjpa06Lr1D_kO_zflSv30ztbnfANQlGn68Gbr_qexlkeo50qLOKK2wMt1RX8wstsQEO8f2dNMg',
  },
  {
    id: '2',
    departure: 'Bureau, 12 Rue de la Paix',
    destination: 'Aéroport Charles de Gaulle',
    departureCoords: { lat: 48.8686, lng: 2.3299 },
    destinationCoords: { lat: 49.0097, lng: 2.5479 },
    date: '14 Oct.',
    time: '18:45',
    price: 52.00,
    seats: 2,
    status: 'pending',
    driver: {
      name: 'Jean-Pierre L.',
      avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA3zU6lSuACMFHSnlUYXJ5f3q7yut0DGOEeOiTlKp0r5-m6HajEzaMJaWTQ_gwCLH-2f3pI4fkCrVgcK8BEKZ2zjdxwzOE2VUXhhM7yo5SbIvgbNPy4U9XCmjNEQlVJegngdNaaqdKRhRtdwak56tQEdB-Tvoi1vTpKKPdg68yydqZigpBH_NUQZsjE4kALSUvR6lfGKHWgfnT1V3SY7kZJQ0gGrEStEot4ooFreXD8WoNhb08tYhgOgzPL-OpVlwRDKMc5yl0-7J0',
      rating: 4.7,
      trips: 856,
      reliabilityScore: 95,
      vehicle: {
        model: 'Peugeot 3008',
        color: 'Noir',
        type: 'Hybride',
        plate: 'BC-456-DE',
        image: '',
      },
    },
    createdAt: now - 15 * 60 * 1000,
    mapImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUCa3dSGTbpGWXcMm33bcgtSz1ua1SgTtY1UsakZA0lWmxj5gsH2nnfAoLvFbeWLa67eiqemCQj4u9_40KMPvaL_Gz5RH5_avOjFuHSCsddEM5l0ncW8YMidPNmu4CxxSn6_GcILpxOHzltcKii9P7IM4xEBVi3EtcI5vdi5IFbQftAaDX6NA8rSOQmkRjVZCrpSKWY6Td_sjpp4cc4Ri23s9kMxcVHcUDGMf0raCsXutFW1D-spGlGLPzq1G14bz1xq3QFr1YOL0',
  },
  {
    id: '3',
    departure: 'Gare de Lyon, Paris',
    destination: 'Gare Montparnasse',
    departureCoords: { lat: 48.8443, lng: 2.3735 },
    destinationCoords: { lat: 48.8422, lng: 2.3219 },
    date: '10 Oct.',
    time: '14:00',
    price: 18.00,
    seats: 1,
    status: 'completed',
    driver: {
      name: 'Sophie M.',
      avatar: '',
      rating: 4.8,
      trips: 320,
      reliabilityScore: 97,
      vehicle: {
        model: 'Renault Zoé',
        color: 'Bleu',
        type: 'Électrique',
        plate: 'EF-789-GH',
        image: '',
      },
    },
    createdAt: now - 3 * 24 * 60 * 60 * 1000,
    mapImage: '',
  },
  {
    id: '4',
    departure: 'Paris Gare de Lyon',
    destination: 'Marseille Saint-Charles',
    departureCoords: { lat: 48.8443, lng: 2.3735 },
    destinationCoords: { lat: 43.3026, lng: 5.3806 },
    date: '16 Oct.',
    time: '07:00',
    price: 45.00,
    seats: 3,
    status: 'confirmed',
    driver: {
      name: 'Camille D.',
      avatar: '',
      rating: 4.8,
      trips: 534,
      reliabilityScore: 96,
      vehicle: { model: 'Citroën C5 X', color: 'Gris', type: 'Hybride', plate: 'FG-321-HI', image: '' },
    },
    createdAt: now - 2 * 60 * 1000,
    mapImage: '',
  },
  {
    id: '5',
    departure: 'Toulouse Matabiau',
    destination: 'Bordeaux Saint-Jean',
    departureCoords: { lat: 43.6113, lng: 1.4538 },
    destinationCoords: { lat: 44.8258, lng: -0.5567 },
    date: '17 Oct.',
    time: '09:15',
    price: 32.00,
    seats: 4,
    status: 'pending',
    driver: {
      name: 'Léo R.',
      avatar: '',
      rating: 4.6,
      trips: 210,
      reliabilityScore: 93,
      vehicle: { model: 'Volkswagen ID.4', color: 'Bleu', type: 'Électrique', plate: 'JK-654-LM', image: '' },
    },
    createdAt: now - 8 * 60 * 1000,
    mapImage: '',
  },
  {
    id: '6',
    departure: 'Lyon Part-Dieu',
    destination: 'Marseille Saint-Charles',
    departureCoords: { lat: 45.7602, lng: 4.8597 },
    destinationCoords: { lat: 43.3026, lng: 5.3806 },
    date: '18 Oct.',
    time: '11:30',
    price: 28.00,
    seats: 2,
    status: 'confirmed',
    driver: {
      name: 'Inès B.',
      avatar: '',
      rating: 4.9,
      trips: 678,
      reliabilityScore: 99,
      vehicle: { model: 'BMW iX1', color: 'Blanc', type: 'Électrique', plate: 'NO-987-PQ', image: '' },
    },
    createdAt: now - 4 * 60 * 1000,
    mapImage: '',
  },
  {
    id: '7',
    departure: 'Paris Montparnasse',
    destination: 'Nantes Gare Sud',
    departureCoords: { lat: 48.8422, lng: 2.3219 },
    destinationCoords: { lat: 47.2172, lng: -1.5425 },
    date: '19 Oct.',
    time: '06:45',
    price: 38.00,
    seats: 3,
    status: 'pending',
    driver: {
      name: 'Thomas G.',
      avatar: '',
      rating: 4.5,
      trips: 145,
      reliabilityScore: 91,
      vehicle: { model: 'Renault Mégane E-Tech', color: 'Rouge', type: 'Électrique', plate: 'RS-111-TU', image: '' },
    },
    createdAt: now - 12 * 60 * 1000,
    mapImage: '',
  },
  {
    id: '8',
    departure: 'Lille Flandres',
    destination: 'Paris Gare du Nord',
    departureCoords: { lat: 50.6365, lng: 3.0700 },
    destinationCoords: { lat: 48.8809, lng: 2.3553 },
    date: '20 Oct.',
    time: '16:00',
    price: 22.00,
    seats: 4,
    status: 'confirmed',
    driver: {
      name: 'Émilie V.',
      avatar: '',
      rating: 4.7,
      trips: 390,
      reliabilityScore: 94,
      vehicle: { model: 'Peugeot e-208', color: 'Vert', type: 'Électrique', plate: 'VW-222-XY', image: '' },
    },
    createdAt: now - 6 * 60 * 1000,
    mapImage: '',
  },
  {
    id: '9',
    departure: 'Strasbourg Gare Centrale',
    destination: 'Lyon Part-Dieu',
    departureCoords: { lat: 48.5852, lng: 7.7339 },
    destinationCoords: { lat: 45.7602, lng: 4.8597 },
    date: '21 Oct.',
    time: '08:00',
    price: 42.00,
    seats: 2,
    status: 'pending',
    driver: {
      name: 'Hugo M.',
      avatar: '',
      rating: 4.4,
      trips: 88,
      reliabilityScore: 90,
      vehicle: { model: 'Dacia Spring', color: 'Orange', type: 'Électrique', plate: 'ZA-333-BC', image: '' },
    },
    createdAt: now - 9 * 60 * 1000,
    mapImage: '',
  },
  {
    id: '10',
    departure: 'Bordeaux Saint-Jean',
    destination: 'Toulouse Matabiau',
    departureCoords: { lat: 44.8258, lng: -0.5567 },
    destinationCoords: { lat: 43.6113, lng: 1.4538 },
    date: '22 Oct.',
    time: '13:30',
    price: 30.00,
    seats: 3,
    status: 'confirmed',
    driver: {
      name: 'Clara F.',
      avatar: '',
      rating: 4.8,
      trips: 456,
      reliabilityScore: 97,
      vehicle: { model: 'Tesla Model Y', color: 'Noir', type: 'Électrique', plate: 'DE-444-FG', image: '' },
    },
    createdAt: now - 3 * 60 * 1000,
    mapImage: '',
  },
];

export const mockTransactions: Transaction[] = [
  { id: 't1', type: 'payment', label: 'Paiement trajet', amount: 45.00, date: 'Hier, 18:45', icon: 'directions_car' },
  { id: 't2', type: 'penalty_received', label: 'Pénalité reçue', amount: -15.00, date: '12 Oct, 14:20', icon: 'gavel' },
  { id: 't3', type: 'penalty_paid', label: 'Pénalité payée', amount: -15.00, date: '10 Oct, 09:15', icon: 'account_balance' },
  { id: 't4', type: 'refund', label: 'Remboursement', amount: 12.50, date: '08 Oct, 16:30', icon: 'undo' },
];

export const mockNotifications: AppNotification[] = [
  { id: 'n1', type: 'ride_confirmed', title: 'Trajet confirmé', body: 'Votre trajet vers CDG avec Marc-Antoine P. est confirmé pour demain à 08:30.', time: 'Il y a 2h', read: false, rideId: '1' },
  { id: 'n2', type: 'message', title: 'Nouveau message', body: 'Marc-Antoine P. vous a envoyé un message.', time: 'Il y a 3h', read: false, rideId: '1' },
  { id: 'n3', type: 'payment', title: 'Paiement reçu', body: 'Vous avez reçu 45,00 € pour votre trajet.', time: 'Hier', read: true },
  { id: 'n4', type: 'penalty', title: 'Pénalité appliquée', body: 'Une pénalité de 15,00 € a été appliquée suite à une annulation tardive.', time: '12 Oct.', read: true },
];

export const mockReviews: Review[] = [
  { id: 'r1', rideId: '3', driverName: 'Sophie M.', rating: 5, comment: 'Trajet très agréable, conduite souple et ponctuelle !', date: '10 Oct.' },
  { id: 'r2', rideId: '3', driverName: 'Julien Lefebvre', rating: 4, comment: 'Bon trajet, voiture propre.', date: '10 Oct.' },
];

export const mockMessages: ChatMessage[] = [
  { id: 'm1', rideId: '1', sender: 'remote', text: 'Bonjour ! Je suis arrivé au point de rendez-vous avec la Peugeot 3008 noire. Je suis garé juste devant la boulangerie.', time: '14:22' },
  { id: 'm2', rideId: '1', sender: 'user', text: "Parfait, j'arrive dans 2 minutes. Je porte une veste bleue.", time: '14:23' },
  { id: 'm3', rideId: '1', sender: 'system', text: 'Conversation sécurisée — Vos données et votre numéro de téléphone sont protégés par le système de cryptage Roulii.', time: '' },
  { id: 'm4', rideId: '1', sender: 'remote', text: "C'est noté. À tout de suite !", time: '14:25' },
  { id: 'm5', rideId: '1', sender: 'system', text: 'Julien a confirmé sa présence.', time: '' },
  { id: 'm6', rideId: '4', sender: 'system', text: 'Conversation sécurisée — Vos données sont protégées par Roulii.', time: '' },
  { id: 'm7', rideId: '4', sender: 'remote', text: 'Bonjour ! On se retrouve devant la Gare de Lyon, entrée principale. Je serai en Citroën C5 grise.', time: '18:00' },
  { id: 'm8', rideId: '4', sender: 'user', text: 'Super, merci ! On fait un arrêt sur l\'aire d\'autoroute ?', time: '18:05' },
  { id: 'm9', rideId: '4', sender: 'remote', text: 'Oui bien sûr, pause café vers Valence, ça vous convient ?', time: '18:07' },
  { id: 'm10', rideId: '5', sender: 'system', text: 'Conversation sécurisée — Vos données sont protégées par Roulii.', time: '' },
  { id: 'm11', rideId: '5', sender: 'remote', text: 'Bonjour ! Départ prévu à 9h15 de Matabiau. J\'ai un VW ID.4 bleu, impossible de le rater !', time: '20:30' },
  { id: 'm12', rideId: '6', sender: 'system', text: 'Conversation sécurisée — Vos données sont protégées par Roulii.', time: '' },
  { id: 'm13', rideId: '6', sender: 'remote', text: 'Bonjour Julien ! RDV devant Part-Dieu côté Villette. BMW iX1 blanche.', time: '09:00' },
  { id: 'm14', rideId: '6', sender: 'user', text: 'Parfait, à quelle heure exactement ?', time: '09:10' },
  { id: 'm15', rideId: '6', sender: 'remote', text: '11h15, 15 min avant le départ pour charger les bagages.', time: '09:12' },
  { id: 'm16', rideId: '8', sender: 'system', text: 'Conversation sécurisée — Vos données sont protégées par Roulii.', time: '' },
  { id: 'm17', rideId: '8', sender: 'remote', text: 'Salut ! Je pars de Lille Flandres à 16h. Place pour 4, n\'hésitez pas à ramener un ami !', time: '12:00' },
  { id: 'm18', rideId: '10', sender: 'system', text: 'Conversation sécurisée — Vos données sont protégées par Roulii.', time: '' },
  { id: 'm19', rideId: '10', sender: 'remote', text: 'Hello ! Trajet Bordeaux → Toulouse, départ 13h30. Tesla Model Y noire, je serai au parking Kiss & Ride.', time: '10:00' },
  { id: 'm20', rideId: '10', sender: 'user', text: 'Merci Clara, j\'ai un gros sac à dos, ça passe dans le coffre ?', time: '10:15' },
  { id: 'm21', rideId: '10', sender: 'remote', text: 'Aucun souci, le coffre est immense ! À demain.', time: '10:17' },
];
